[workspace]
resolver = "3"
members = [
    "cli",
    "compiler",
    "frontend", 
    "op", 
    "runtime",
]

[workspace.dependencies] 
owo-colors = "4.3.0"
clap = { version = "4.6.6", features = ["derive"] }
frontend = { path = "frontend" }
compiler = { path = "compiler" }
runtime = { path = "runtime" }
cli = { path = "cli" }
