[[opcodes]]
name = "halt"
value = 0
description = "halts execution of the virtual machine"

[[opcodes]]
name = "iadd"
value = 1
description = "pops 2 ints off the stack and adds them then pushes the result"

[[opcodes]]
name = "isub"
value = 2
description = "pops 2 ints off the stack and subtracts them then pushes the result"

[[opcodes]]
name = "imul"
value = 3
description = "pops 2 ints off the stack and multiplies them then pushes the result"

[[opcodes]]
name = "idiv"
value = 4
description = "pops 2 ints off the stack and divides them then pushes the result"

[[opcodes]]
name = "loadconst"
value = 5
description = "takes a 3 byte operand and indexes into constant pool and pushes the value at index operand"

[[opcodes]]
name = "iprint"
value = 6
description = "pops 1 int off the stack and prints it"